// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

// export const metadata = {
  // title: "EV Insights - Electric Vehicle News & Reviews",
  // description:
  //   "Latest EV news, electric car reviews, charging guides, battery technology and EV updates in India.",
//   title: {
//     default: "EV Insights Hub",
//     template: "%s | EV Insights Hub",
//   },

//   openGraph: {
//   title: "EV Insights Hub",
//   description: "Latest EV News & Reviews",
//   type: "website",
// },
//   description:
//     "Latest EV news, reviews, charging guides and electric vehicle updates.",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  metadataBase: new URL("https://evinsightshub.in"),

  title: {
    default: "EV Insight Hub",
    template: "%s | EV Insight Hub",
  },

  description:
    "Latest EV news, reviews, comparisons and buying guides.",

  openGraph: {
    title: "EV Insight Hub",
    description: "Latest EV News & Reviews",
    url: "https://evinsightshub.in",
    siteName: "EV Insight Hub",
    type: "website",
  },
};

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       suppressHydrationWarning
//       className={`${geistSans.variable} ${geistMono.variable}`}
//     >
//       <body>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>

      <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-X89F8BE3WF"
        strategy="afterInteractive"
      />

      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-X89F8BE3WF');
        `}
      </Script>
    </html>
  );
}


