import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

export const metadata = {
  // title: "EV Insights - Electric Vehicle News & Reviews",
  // description:
  //   "Latest EV news, electric car reviews, charging guides, battery technology and EV updates in India.",
  title: {
    default: "EV Insights Hub",
    template: "%s | EV Insights Hub",
  },

  openGraph: {
  title: "EV Insights Hub",
  description: "Latest EV News & Reviews",
  type: "website",
},
  description:
    "Latest EV news, reviews, charging guides and electric vehicle updates.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

